--1
-- Create view Critical Teacher Information
USE QLDT

CREATE VIEW THONGTINGVPB
AS
SELECT DISTINCT GV_PBDT.MSGV, TENGV, SODT, DIACHI,TENHV,TENHH
FROM GV_PBDT, GV_HV_CN AS A, HOCVI,HOCHAM, GIAOVIEN
WHERE GV_PBDT.MSGV =GIAOVIEN.MSGV AND GV_PBDT.MSGV =A.MSGV AND A.MSHV =HOCVI.MSHV AND GIAOVIEN.MSHH=HOCHAM.MSHH
AND HOCVI.TENHV = (
	SELECT TENHV FROM HOCVI WHERE MSHV = A.MSHV AND MSHV = (SELECT MAX(MSHV) FROM GV_HV_CN WHERE MSGV = A.MSGV))
--2
-- Create view Information about the topic evaluation council
CREATE VIEW THONGTINHD
AS
SELECT DISTINCT HOIDONG.MSHD,TENDT,PHONG,NGAYHD, TENGV, A.KQ
FROM HOIDONG, DETAI, GIAOVIEN, HOIDONG_DT, 
	(SELECT MSSV, MSDT, DBO.DTB_DT(MSDT)AS KQ
	FROM SV_DETAI
	GROUP BY MSSV, MSDT
	) AS A
WHERE HOIDONG.MSHD = HOIDONG_DT.MSHD AND HOIDONG_DT.MSDT = DETAI.MSDT AND GIAOVIEN.MSGV = HOIDONG.MSGV AND A.MSDT = DETAI.MSDT