--A.STORED PROCEDUREDS--
--1--
-- Before inserting data, check if MSHH exists in the HOCHAM table
CREATE PROCEDURE PROC_INSERT_GIAOVIEN_MSHH
	(OUT @MSGV INT, IN @TENGV VARCHAR (30), IN @SODT VARCHAR (10), IN @DIACHI VARCHAR (50),
	IN @MSHH INT,  IN @NAMHH YEAR)
BEGIN
	IF EXISTS (SELECT * FROM HOCHAM WHERE MSHH = @MSHH)
		BEGIN
			INSERT INTO GIAOVIEN VALUES (@MSGV, @TENGV,@DIACHI, @SODT, @MSHH, @NAMHH)
			PRINT N'THÀNH CÔNG'
		END //
	ELSE
		BEGIN
			PRINT N'MSHH KHÔNG TỒN TẠI'
			RETURN 0
		END //
END
--THUC THI
EXEC PROC_INSERT_GIAOVIEN_MSHH @MSGV = 00207, @TENGV = 'Nguyen Thi C', @DIACHI = 'TPHCM',  @SODT = '0123456789', @MSHH = '2', @NAMHH = '2010'
EXEC PROC_INSERT_GIAOVIEN_MSHH @MSGV = 00206, @TENGV = N'Tran Anh Hao',@DIACHI = 'Hoc Mon', @SODT = '0902150008',  @MSHH = '1', @NAMHH = '2020'
EXEC PROC_INSERT_GIAOVIEN_MSHH @MSGV = 00206, @TENGV = N'Nguyen Van B',  @DIACHI = 'Hoc Mon', @SODT = '0902150008', @MSHH = '3', @NAMHH = '2020'
--2--
-- Before inserting data, check if the MSGV in the GIAOVIEN table is the same
GO
CREATE PROCEDURE PROC_INSERT_GIAOVIEN_MSGV
	@MSGV INT, @TENGV NVARCHAR (30), @SODT VARCHAR (10), @DIACHI NVARCHAR (50),
	@MSHH INT, @NAMHH SMALLDATETIME
AS
BEGIN
	IF EXISTS (SELECT * FROM GIAOVIEN WHERE MSGV = @MSGV)
		BEGIN
			PRINT N'MSGV ĐÃ TỒN TẠI'
			RETURN 0			
		END
	ELSE
		BEGIN
			INSERT INTO GIAOVIEN VALUES (@MSGV, @TENGV,@DIACHI, @SODT, @MSHH, @NAMHH)
			PRINT N'THÀNH CÔNG'
		END
END
--THUC THI
EXEC PROC_INSERT_GIAOVIEN_MSHH @MSGV = 00207, @TENGV = 'Nguyen Thi C', @DIACHI = 'TPHCM',  @SODT = '0123456789', @MSHH = '2', @NAMHH = '2010'
EXEC PROC_INSERT_GIAOVIEN_MSHH @MSGV = 00207, @TENGV = 'Nguyen Thi D', @DIACHI = 'TPHCM',  @SODT = '0123456789', @MSHH = '2', @NAMHH = '2010'
--3--
--Check to see if MSGV is the same? MSHH does exist yet?
GO
CREATE PROCEDURE PROC_INSERT_GIAOVIEN_MSGV_MSHH
	@MSGV INT, @TENGV NVARCHAR (30), @SODT VARCHAR (10), @DIACHI NVARCHAR (50),
	@MSHH INT, @NAMHH SMALLDATETIME
AS
BEGIN
	IF EXISTS (SELECT * FROM GIAOVIEN WHERE MSGV = @MSGV)
		BEGIN
			PRINT N'MSGV ĐÃ TỒN TẠI'
			RETURN 0			
		END
	IF NOT EXISTS (SELECT * FROM HOCHAM WHERE MSHH = @MSHH) AND @MSHH IS NOT NULL
		BEGIN
			PRINT N'MSHH CHƯA TỒN TẠI'
			RETURN 1			
		END
	ELSE
		BEGIN
			INSERT INTO GIAOVIEN VALUES (@MSGV, @TENGV,@DIACHI, @SODT, @MSHH, @NAMHH)
			PRINT N'THÀNH CÔNG'
		END
END
--THUC THI
EXEC PROC_INSERT_GIAOVIEN_MSHH @MSGV = 00207, @TENGV = 'Nguyen Thi D', @DIACHI = 'TPHCM',  @SODT = '0123456789', @MSHH = '2', @NAMHH = '2010'
--4
-- Update the new topic name with the old topic code unchanged
GO
CREATE PROCEDURE PROC_UPDATE_DETAI_TENDT
	@MSDT CHAR(6), @TENDT NVARCHAR (30)
AS
BEGIN
	IF EXISTS (SELECT * FROM DETAI WHERE MSDT = @MSDT)
		BEGIN
			UPDATE DETAI SET TENDT=@TENDT WHERE MSDT = @MSDT 
			RETURN 1			
		END
	ELSE
		BEGIN
			PRINT N'KHONG TIM THAY MSDT'
			RETURN 0
		END
END
--THUC THI
EXEC PROC_UPDATE_DETAI_TENDT @MSDT = 97001 , @TENDT = N'Quản lý thư viện'
EXEC PROC_UPDATE_DETAI_TENDT @MSDT = 97007 , @TENDT = N'Quản lý thư viện'
--5
-- Parameters put into MSSV, new TENSV, new DIACHI are used to update students
GO
CREATE PROCEDURE PROC_UPDATE_SINHVIEN_TENSV_DIACHI
	@MSSV CHAR(8), @TENSV NVARCHAR (30), @DIACHI NVARCHAR(50)
AS
BEGIN
	IF EXISTS (SELECT * FROM SINHVIEN WHERE MSSV = @MSSV)
		BEGIN
			UPDATE SINHVIEN SET TENSV=@TENSV, DIACHI=@DIACHI WHERE MSSV = @MSSV 
			RETURN 1			
		END
	ELSE
		BEGIN
			PRINT N'KHONG TIM THAY MSSV'
			RETURN 0
		END
END
--THUC THI
EXEC PROC_UPDATE_SINHVIEN_TENSV_DIACHI @MSSV=13520001, @TENSV=N'Nguyễn Văn An', @DIACHI=N'Thủ Đức'

--B--
--1
-- Put into TENHV and return the number of teachers with qualifications
GO
CREATE PROCEDURE PROC_SOGV_BY_HOCVI
	@TENHV NVARCHAR (20), @SOGV INT OUTPUT
AS
BEGIN
	IF EXISTS (SELECT * FROM HOCVI WHERE TENHV = @TENHV)
		BEGIN
			SELECT @SOGV = COUNT (*) 
			FROM HOCVI, GV_HV_CN
			WHERE HOCVI.MSHV = GV_HV_CN.MSHV AND HOCVI.TENHV = @TENHV
		END
	ELSE
		SET @SOGV = 0
END
GO

DECLARE @TENHV NVARCHAR (20), @SOGV INT
SET @TENHV = N'Thac si'

EXEC PROC_SOGV_BY_HOCVI @TENHV, @SOGV OUTPUT
PRINT N'Số GV có học vị ' + @TENHV + N' là: ' + CAST (@SOGV AS NVARCHAR)
--2
--Put into the MSDT returns the average score of the topic
GO
CREATE PROCEDURE TINHDTB_DT
	@MSDT CHAR (6), @DIEMTRUNGBINH FLOAT OUTPUT
AS
BEGIN
	IF EXISTS (SELECT * FROM GV_HDDT WHERE MSDT=@MSDT)
	BEGIN
		SELECT @DIEMTRUNGBINH = AVG(DIEM) 
		FROM (
		SELECT * FROM GV_HDDT UNION
		SELECT * FROM GV_UVDT UNION
		SELECT * FROM GV_PBDT ) AS DIEMTONGHOP
		WHERE MSDT = @MSDT
	END
	ELSE
		SET @DIEMTRUNGBINH = 0
END
GO
DECLARE @MSDT CHAR (6), @DIEMTRUNGBINH FLOAT
SET @MSDT='97001'

EXEC TINHDTB_DT @MSDT,@DIEMTRUNGBINH OUTPUT
PRINT N'Điểm trung bình của đề tài ' + @MSDT + N' là: ' + CAST (@DIEMTRUNGBINH AS NVARCHAR)
--3
-- Put into TENGV returns the phone number (SDT) of that teacher
GO
CREATE PROCEDURE GETSDT_OFGV
	@TENGV NVARCHAR (30), @SODT VARCHAR(10) OUTPUT
AS
BEGIN
	IF EXISTS (SELECT * FROM GIAOVIEN WHERE TENGV=@TENGV)
	BEGIN
		DECLARE @GVTRUNG INT = ( SELECT COUNT(*) FROM GIAOVIEN WHERE TENGV=@TENGV)
		IF @GVTRUNG > 1
		BEGIN
			RAISERROR (N'CÓ %d GIÁO VIÊN TRÙNG TÊN.',16,1,@GVTRUNG)
		END
		ELSE
		BEGIN
			SELECT @SODT=SODT FROM GIAOVIEN WHERE TENGV=@TENGV
		END
	END
	ELSE
	BEGIN
		SELECT 0;
	END
END
GO
DECLARE @TENGV NVARCHAR (30),@SODT VARCHAR(10)
SET @TENGV=N'Nguyen Van An'

EXEC GETSDT_OFGV @TENGV,@SODT OUTPUT
IF @SODT IS NULL
BEGIN 
	PRINT 'KHONG TIM THAY SDT CUA GIAO VIEN : ' + @TENGV
END
ELSE
BEGIN
	PRINT 'SO DIEN THOAI CUA GIAO VIEN '+@TENGV + ' LA: ' +@SODT
END
--4
-- Put into MSHD returns the average score of the topics of that council
GO
CREATE PROCEDURE DTB_DT_HD
	@MSHD INT, @DTB FLOAT OUTPUT
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM HOIDONG WHERE MSHD=@MSHD)
	BEGIN
		SET @DTB=0;
		RETURN;
	END
	SELECT @DTB=AVG(DIEM)
	FROM (
	SELECT * FROM GV_HDDT UNION
		SELECT * FROM GV_UVDT UNION
		SELECT * FROM GV_PBDT ) AS DIEMTONGHOP
		WHERE MSDT IN (
			SELECT MSDT
			FROM HOIDONG_DT
			WHERE MSHD=@MSHD )
END

DECLARE @MSHD INT=1, @DTB FLOAT
EXEC DTB_DT_HD @MSHD, @DTB OUTPUT
IF @DTB=0
BEGIN 
	PRINT 'KHONG TIM THAY HOI DONG CO MA SO ' + CAST(@MSHD AS VARCHAR)
END
ELSE
BEGIN
	PRINT 'DTB CUA DE TAI CUA HOI DONG '+CAST(@MSHD AS VARCHAR) + ' LA: ' +CAST(@DTB AS VARCHAR)
END
-- 5
-- Put into TENGV returns the number of instructional topics and the number of critical topics in charge of that teacher.
GO
CREATE PROCEDURE GV_HD_PB_DT
	@TENGV NVARCHAR (30), @SODETAI_HD INT OUTPUT, @SODETAI_PB INT OUTPUT
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM GIAOVIEN WHERE TENGV=@TENGV)
	BEGIN
		PRINT 'KHONG TIM THAY GIAO VIEN ' + @TENGV
		RETURN
	END
	DECLARE @MSGV INT
	SELECT @MSGV=MSGV FROM GIAOVIEN WHERE TENGV=@TENGV
	IF EXISTS (SELECT * FROM GIAOVIEN WHERE TENGV=@TENGV)
	BEGIN
		SELECT @SODETAI_HD=COUNT(*) FROM GV_HDDT WHERE MSGV=@MSGV
		SELECT @SODETAI_PB=COUNT(*) FROM GV_PBDT WHERE MSGV=@MSGV
	END
	ELSE
	BEGIN
		SET @SODETAI_HD=0
		SET @SODETAI_PB=0
	END
END
GO

DECLARE @TENGV NVARCHAR(30),@SODETAI_HD INT, @SODETAI_PB INT
SET @TENGV='Nguyen Van An'

EXEC GV_HD_PB_DT @TENGV,@SODETAI_HD OUTPUT, @SODETAI_PB OUTPUT

PRINT 'SO DE TAI HUONG DAN CUA GIAO VIEN '+@TENGV+' LA ' + CAST(@SODETAI_HD AS NVARCHAR)
PRINT 'SO DE TAI PHAN BIEN CUA GIAO VIEN '+@TENGV+' LA ' + CAST(@SODETAI_PB AS NVARCHAR)