-- C--
-- 1
-- Triggers that satisfy the condition of deleting a topic will delete related information
GO
CREATE TRIGGER DELETE_DETAI
ON DETAI
INSTEAD OF DELETE
AS
BEGIN
	DECLARE @MSDT CHAR(6)
	SELECT @MSDT=MSDT FROM deleted
	DELETE FROM SV_DETAI
	WHERE MSDT=@MSDT
	DELETE FROM GV_HDDT
	WHERE MSDT=@MSDT
	DELETE FROM GV_PBDT
	WHERE MSDT=@MSDT
	DELETE FROM GV_UVDT
	WHERE MSDT=@MSDT
	DELETE FROM HOIDONG_DT
	WHERE MSDT=@MSDT
	PRINT 'DA XOA CAC THONG TIN LIEN QUAN!'
END
-- THUC THI
DELETE DETAI
WHERE MSDT='97001'
-- 2
-- The trigger satisfies the constraint that an assembly has no more than 10 topics
GO
CREATE TRIGGER TRIG_INSERT_HD_DT_SLDT
ON HOIDONG_DT
FOR INSERT
AS
BEGIN
	IF (SELECT COUNT (*)
		FROM INSERTED, HOIDONG_DT
		WHERE INSERTED.MSHD = HOIDONG_DT.MSHD) > 3
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR (N'MỘT HD KHÔNG QUÁ 10 ĐỀ TÀI', 16, 1)
		RETURN
	END
END
INSERT INTO HOIDONG_DT VALUES (1, '97003', 'Duoc')
INSERT INTO HOIDONG_DT VALUES (2, '97006', 'Duoc')
-- 3
-- Trigger that satisfies constraints is a topic of no more than 3 students
GO
CREATE TRIGGER TRIG_INSERT_DT_SLSV
ON SV_DETAI
AFTER INSERT, UPDATE
AS
BEGIN
	DECLARE @MSDT CHAR(6)
	SELECT @MSDT=MSDT FROM inserted
	IF (SELECT COUNT(*) FROM SV_DETAI WHERE MSDT=@MSDT)>3
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR ('MOT DE TAI KHONG QUA 3 SINH VIEN!', 16, 1)
	END
END
-- 4
-- Trigger satisfies the constraint that a teacher who wants an associate professor degree must have a doctorate
GO
CREATE TRIGGER TRIG_UPDATE_GV_PGS
ON GIAOVIEN
FOR UPDATE
AS
BEGIN
	IF EXISTS(
	SELECT *
	FROM inserted T
	JOIN GIAOVIEN GV ON I.MSGV=GV.MSGV
	JOIN GV_HV_CN ON I.MSGV=GV_HV_CN.MSGV
	WHERE I.MSGV=1 AND GV_HV_CN.MSHV <>1 )
	BEGIN
		RAISERROR ('GIAO VIEN MUON LA PGS PHAI LA TIEN SI TRUOC!', 16, 1)
		ROLLBACK TRANSACTION
	END
END
--5 
--Trigger satisfies The teacher who is the chairman of the council must have a doctorate degree
-- Ràng buộc thao tác xóa trên bảng GV_HV_CN
CREATE TRIGGER TRIG_DELETE_GV_HV_CN
ON GV_HV_CN
FOR DELETE
AS
BEGIN
	DECLARE @MSGV INT
	SELECT @MSGV = MSGV FROM deleted
	IF(SELECT MSHV FROM GV_HV_CN WHERE MSGV = @MSGV) = 4
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR(N'GIÁO VIÊN LÀ CHỦ TỊCH HỘI ĐỒNG PHẢI CÓ HỌC VỊ TIẾN SĨ',16,1)
			RETURN
		END
END
GO
-- Check trigger
DELETE FROM GV_HV_CN
WHERE MSGV = '201' AND MSCN = '2'
-- Ràng buộc thao tác sửa trên bảng GV_HV_CN
CREATE TRIGGER TRIG_UPDATE_GV_HV
ON GV_HV_CN
FOR UPDATE
AS
BEGIN
	DECLARE @MSGV INT
	DECLARE @MSHV INT
	SELECT @MSGV = MSGV FROM inserted
	SELECT @MSHV = MSHV FROM inserted
	IF(SELECT MSHV FROM GV_HV_CN WHERE MSGV = @MSGV)= 4 AND @MSHV != 4
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR(N'GIÁO VIÊN LÀ CHỦ TỊCH HỘI ĐỒNG PHẢI CÓ HỌC VỊ TIẾN SĨ',16,1)
			RETURN
		END
END
GO
-- CHECK
UPDATE GV_HV_CN
SET MSHV = 3 WHERE MSGV = '201' AND MSCN = '2'
-- Ràng buộc thao tác sửa trên bảng HOCVI
CREATE TRIGGER TRIG_UPDATE_HV
ON HOCVI
FOR UPDATE
AS
BEGIN
	DECLARE @MSHV INT
	DECLARE @TENHV NVARCHAR(20)
	SELECT @MSHV = MSHV FROM inserted
	SELECT @TENHV = TENHV FROM inserted
	IF @MSHV= 4 AND (SELECT TENHV FROM HOCVI WHERE MSHV = @MSHV) != 'Tiến sĩ'
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR(N'GIÁO VIÊN LÀ CHỦ TỊCH HỘI ĐỒNG PHẢI CÓ HỌC VỊ TIẾN SĨ',16,1)
			RETURN
		END
END
GO 
-- Check
UPDATE HOCVI
SET TENHV = 'Kỹ sư' WHERE MSHV = 4
-- Ràng buộc thao tác thêm trên bảng HOIDONG
CREATE TRIGGER TRIG_INSERT_HOIDONG
ON HOIDONG
FOR INSERT
AS
BEGIN
	DECLARE @MSGV INT
	SELECT @MSGV = MSGV FROM inserted
	IF (SELECT MSHV FROM GV_HV_CN WHERE MSGV = @MSGV) != 4 
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR(N'GIÁO VIÊN LÀ CHỦ TỊCH HỘI ĐỒNG PHẢI CÓ HỌC VỊ TIẾN SĨ',16,1)
			RETURN
		END
END
GO
--CHECK
INSERT INTO HOIDONG (MSHD, PHONG, TGBD, NGAYHD, TINGTRANG, MSGV) VALUES ('4', '003', '8:00', '6/12/2014', 'That', '204')
-- Ràng buộc thao tác xóa trên bảng GV_HV_CN
CREATE TRIGGER TRIG_UPDATE_HOIDONG
ON HOIDONG
FOR UPDATE
AS
BEGIN
	DECLARE @MSGV INT
	SELECT @MSGV = MSGV FROM inserted
	IF (SELECT MSHV FROM GV_HV_CN WHERE MSGV = @MSGV) != 4  
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR(N'GIÁO VIÊN LÀ CHỦ TỊCH HỘI ĐỒNG PHẢI CÓ HỌC VỊ TIẾN SĨ',16,1)
			RETURN
		END
END
GO
--CHECK
UPDATE HOIDONG
SET MSGV = 204 WHERE MSHD = 3