-- C--
-- 1
GO
CREATE TRIGGER DELETE_DETAI
ON DETAI
INSTEAD OF DELETE
AS
BEGIN
	DECLARE @MSDT CHAR(6)
	SELECT @MSDT=MSDT FROM deleted
	DELETE FROM SV_DETAI
	WHERE MSDT=@MSDT
	DELETE FROM GV_HDDT
	WHERE MSDT=@MSDT
	DELETE FROM GV_PBDT
	WHERE MSDT=@MSDT
	DELETE FROM GV_UVDT
	WHERE MSDT=@MSDT
	DELETE FROM HOIDONG_DT
	WHERE MSDT=@MSDT
	PRINT 'DA XOA CAC THONG TIN LIEN QUAN!'
END
-- THUC THI
DELETE DETAI
WHERE MSDT='97001'
-- 2
GO
CREATE TRIGGER TRIG_INSERT_HD_DT_SLDT
ON HOIDONG_DT
FOR INSERT
AS
BEGIN
	IF (SELECT COUNT (*)
		FROM INSERTED, HOIDONG_DT
		WHERE INSERTED.MSHD = HOIDONG_DT.MSHD) > 3
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR (N'MỘT HD KHÔNG QUÁ 10 ĐỀ TÀI', 16, 1)
		RETURN
	END
END
INSERT INTO HOIDONG_DT VALUES (1, '97003', 'Duoc')
INSERT INTO HOIDONG_DT VALUES (2, '97006', 'Duoc')
-- 3
GO
CREATE TRIGGER TRIG_INSERT_DT_SLSV
ON SV_DETAI
AFTER INSERT, UPDATE
AS
BEGIN
	DECLARE @MSDT CHAR(6)
	SELECT @MSDT=MSDT FROM inserted
	IF (SELECT COUNT(*) FROM SV_DETAI WHERE MSDT=@MSDT)>3
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR ('MOT DE TAI KHONG QUA 3 SINH VIEN!', 16, 1)
	END
END
-- 4
GO
CREATE TRIGGER TRIG_UPDATE_GV_PGS
ON GIAOVIEN
FOR UPDATE
AS
BEGIN
	IF EXISTS(
	SELECT *
	FROM inserted I
	JOIN GIAOVIEN GV ON I.MSGV=GV.MSGV
	JOIN GV_HV_CN ON I.MSGV=GV_HV_CN.MSGV
	WHERE I.MSGV=1 AND GV_HV_CN.MSHV <>1 )
	BEGIN
		RAISERROR ('GIAO VIEN MUON LA PGS PHAI LA TIEN SI TRUOC!', 16, 1)
		ROLLBACK TRANSACTION
	END
END